# Part of OpenG2P Registry. See LICENSE file for full copyright and licensing details.
{
    "name": "G2P: Proxy Means Test",
    "category": "G2P",
    "version": "15.0.1.1.0",
    "sequence": 1,
    "author": "OpenG2P",
    "website": "https://github.com/openg2p/openg2p-program",
    "license": "Other OSI approved licence",
    "development_status": "Alpha",
    "maintainers": ["jeremi", "gonzalesedwin1123", "emjay0921"],
    "depends": ["g2p_programs", "g2p_program_registrant_info"],
    "data": [
        "security/ir.model.access.csv",
        "views/proxy_means_test_view.xml",
        "views/program_registrant_info.xml",
        "wizard/create_program_pmt_wizard.xml",
    ],
    "assets": {},
    "demo": [],
    "images": [],
    "application": True,
    "installable": True,
    "auto_install": False,
}
