# Part of OpenG2P. See LICENSE file for full copyright and licensing details.

{
    "name": "G2P Programs All",
    "category": "G2P",
    "version": "17.0.1.5.0",
    "sequence": 1,
    "author": "OpenG2P",
    "website": "https://openg2p.org",
    "license": "LGPL-3",
    "depends": [
        "g2p_bridge_configuration",
        "g2p_entitlement_differential",
        "g2p_entitlement_in_kind",
        "g2p_entitlement_voucher",
        "g2p_formio",
        "g2p_mis_importer",
        "g2p_notifications_base",
        "g2p_notifications_fast2sms",
        "g2p_notifications_voucher",
        "g2p_notifications_wiserv",
        "g2p_odk_importer_program",
        "g2p_openid_vci_programs",
        "g2p_payment_cash",
        "g2p_payment_files",
        "g2p_payment_g2p_connect",
        "g2p_payment_interop_layer",
        "g2p_payment_phee",
        "g2p_payment_simple_mpesa",
        "g2p_program_approval",
        "g2p_program_assessment",
        "g2p_program_autoenrol",
        "g2p_program_cycleless",
        "g2p_program_documents",
        "g2p_program_registrant_info",
        "g2p_program_reimbursement",
        "g2p_programs",
        "g2p_programs_priority_list",
        "g2p_proxy_means_test",
        "g2p_reimbursement_portal",
        "g2p_social_registry_importer",
        "g2p_theme",
    ],
    "data": [],
    "application": True,
    "installable": True,
    "auto_install": False,
}
